name: Deploy

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{process.env.HEROKU_API_KEY}}
          heroku_app_name: ${{process.env.HEROKU_APP_NAME}}
          heroku_email: ${{process.env.HEROKU_EMAIL}}
  